YY=YY||{};

YY.airmarket={
	//host:"97.68.192.217",
	//http://airmarket.ca/leaflet-dev/airmarket/airmarket.html
	host:"166.62.82.16",
	//host:"airmarket.ca",
	//host:"localhost",
	//port:9000,
	port:"",
	path:"/airmarket/",
	//path:"/leaflet-dev/airmarket/",
	query_airspace:"query_airspace.php",
	query_airport:"query_airport.php",
	airport_buffer:9.26,
	primary_radius:1.5,
	flyawya_radius:10,
	airport_point_layer:"cfs",
	airport_buffer_layer:"cfs_buffer_84"
};